### ISSUE TITLE
Starting Kapacitor using a config file

### ISSUE THREAD

**Issue by rainierwolfcastle** [influxdata/influxdata-docker#1]
I think the documentation on starting Kapacitor from a config file is incorrect. The documentation states that you can start Kapacitor like this:

`docker run -p 9092:9092 -v $PWD/kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro kapacitord`

Shouldn't it be: 

`docker run -p 9092:9092 -v $PWD/kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro kapacitor kapacitord`

Also, Kapacitor doesn't seem to be picking up the config file. I got everything working by doing:

`docker run -p 9092:9092 -v $PWD/kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro kapacitor kapacitord -config /etc/kapacitor/kapacitor.conf`

Is that correct?

**Comment by jsternberg** [comment]
Looks like this was removed in influxdata/kapacitor#637.

@nathanielc is there a reason this feature was removed?

@rainierwolfcastle I'll update the documentation with the `kapacitord` -> `kapacitor` typo.

**Comment by apsey** [comment]
Both happened to me and I had the same fix (but I used `--config` instead of `-config`)

**Comment by nathanielc** [comment]
@apsey See #703 and #723. Using `-config` should fix the issue, `--config` is not a recognized option.

**Comment by jsternberg** [comment]
I think the automatic pickup of the configuration file has been readded and is in 1.0. I'm going to close this since the documentation was updated and it works again. If something is still not documented correctly, please post here and I'll try to address the issue. Thanks.
