### ISSUE TITLE
Database initialization is not working

### ISSUE THREAD

**Issue by cpang2** [influxdata/influxdata-docker#232]
Tried to create database user and database in docker-compose.yml but it is not working. Nothing gets created. Please advise.

  influxdb:
    image: influxdb:latest
    restart: always
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_ADMIN_USER=USERNAME 
      - INFLUXDB_ADMIN_PASSWORD=PASS 
      - INFLUXDB_DB=DBTEST 
      - INFLUXDB_HTTP_ENABLED=true
      - INFLUXDB_HTTP_AUTH_ENABLED=true

**Comment by dawidchyrzynski** [comment]
Any progress on this? I have the same issue when auth is enabled.

**Comment by dawidchyrzynski** [comment]
I've fixed the issue by escaping "true" value for `INFLUXDB_HTTP_AUTH_ENABLED` variable. My compose service looks like this now:
```
influxdb:
  image: influxdb:latest
  restart: always
  container_name: influxdb
  ports:
    - 8086:8086
  environment:
    INFLUXDB_DB: telemetry
    INFLUXDB_ADMIN_USER: influx_admin
    INFLUXDB_ADMIN_PASSWORD: pass
    INFLUXDB_HTTP_AUTH_ENABLED: "true"
```

@cpang2 can you confirm whether it works for you?

**Comment by jreinert** [comment]
Having the same issue. Passing `true` as a string does not fix it.

**Comment by mmodenesi** [comment]
Same issue, using docker-compose version 1.19.0, build 9e633ef

**Comment by emriviere** [comment]
As mentionned by @PSanetra in another thread, cleaning my influxdb volume fixed it for me (rm -rf /influxDbData)

**Comment by scho** [comment]
I ran into a similar issue. I've set `INFLUXDB_DB`, but no database was created. 

There was an issue with the special characters not being properly escaped. In my case, the database was called `metrics-live` and I had to add quotes to the name, so that it worked (`"metrics-live"`).

**Comment by halfbaked** [comment]
thanks to the comment above from @emriver . cleaning the volume fixed it for me.

**Comment by blockloop** [comment]
My problem was having `influxd` in my `command:`. The docker CMD executes a script which is a proxy to the `influxd` command, which executes all of the init stuff first.

### OLD: 

```yaml
  influxdb:
    image: docker.io/influxdb:latest
    environment:
      - INFLUXDB_DB=prometheus
    volumes:
      - ./influxdb.conf:/etc/influxdb/influxdb.conf
    command:
      - 'influxd'
      - '-config'
      - '/etc/influxdb/influxdb.conf'
```
### NEW: 

```yaml
  influxdb:
    image: docker.io/influxdb:latest
    environment:
      - INFLUXDB_DB=prometheus
    volumes:
      - ./influxdb.conf:/etc/influxdb/influxdb.conf
    command:
      - '-config'
      - '/etc/influxdb/influxdb.conf'
```

**Comment by lchachurski** [comment]
This is what worked for me using docker-compose. Keep in mind it doesn't work well when changing those settings back and forth. Once the database is initialized it will somehow rebel against changes and output weird errors while authenticating. In my case deleting `/tmp/influxdb` directory helped. 

So delete any database dir first and then use the config below:

```
    influxdb:
        environment:
            INFLUXDB_DB: project_dev
            INFLUXDB_ADMIN_USER: admin
            INFLUXDB_ADMIN_PASSWORD: secret
            INFLUXDB_HTTP_AUTH_ENABLED: "true"
        image: influxdb:latest
        ports:
            - "8086:8086"
            - "8087:8082"
        volumes:
            - /tmp/influxdb:/var/lib/influxdb
```

**Comment by Surfict** [comment]
Hello, still have the problem with the current version.

**Comment by cooling75** [comment]
> ... Keep in mind it doesn't work well when changing those settings back and forth. Once the database is initialized it will somehow rebel against changes and output weird errors while authenticating. In my case deleting `/tmp/influxdb` directory helped.
> ```

Thank you for this hint, I struggled with this for hours. Deleting the volume and let docker-compose recreate it solved it.

**Comment by JoshEisele** [comment]
This issue is quite old - is there any hope that it will be fixed at all. Any workaround to set the ADMIN_USER, ADMIN_PASSWORD as well as the option to HTTP_AUTH_ENABLED at initial docker-compose?

**Comment by elboletaire** [comment]
Have anyone tried setting `INIT_USERS: "true"`? Checking the Dockerfile from the project, users ain't created unless you set `INIT_USERS` to true.

Also FYI: You cannot set boolean environment variables in docker compose files without escaping them as strings. This is not a problem with this docker image, but with docker-compose itself (or with docker run, maybe, who knows).

**Comment by elboletaire** [comment]
Checking the `init-influxdb.sh` file, I see that the only way to initialize users in influx is by setting both `INFLUXDB_HTTP_AUTH_ENABLED` and `INFLUXDB_ADMIN_USER`. At the beginning of the `init-influxdb.sh` there's an initialization of a variable named `INIT_USERS`, which is then used to check if db initialization should be made. 

~~~bash
INIT_USERS=$([ ! -z "$AUTH_ENABLED" ] && [ ! -z "$INFLUXDB_ADMIN_USER" ] && echo 1 || echo)
~~~

I have checked it and it properly initializes the db and creates the user if you specify all the required variables.

I've stumbled upon this issue for a different thing though (I'll create a different issue for it right away): if you specify a `command` it's completely ignored, even though it's specified in the official readme:

![imatge](https://user-images.githubusercontent.com/153305/88591929-70ba1280-d05d-11ea-9118-73c146e29576.png)

**Comment by iosonoumberto** [comment]
Hello,
same problem using both latest and 1.8 using docker file

env should be correct (this is from my docker-compose.yml file)

```
    environment:
      INFLUXDB_DB: jlogs
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
```

It should work as I have both ADMIN USER and HTTP AUTH enabled
moreover, inside container, i see the env vars

```
root@335d30cd03d4:/# env | grep INFL
INFLUXDB_DB=jlogs
INFLUXDB_ADMIN_USER=admin
INFLUXDB_HTTP_AUTH_ENABLED=true
INFLUXDB_VERSION=1.8.3
INFLUXDB_ADMIN_PASSWORD=admin
```

so it has everything to create user and db...in theory

i can see these logs

```
[httpd] 127.0.0.1 - - [22/Oct/2020:22:37:28 +0000] "GET /ping HTTP/1.1" 204 0 "-" "InfluxDBShell/1.8.3" 2a348f04-14b7-11eb-8001-0242c0a85002 759
ts=2020-10-22T22:37:28.460603Z lvl=info msg="Executing query" log_id=0Q0cCQ90000 service=query query="CREATE USER admin WITH PASSWORD [REDACTED] WITH ALL PRIVILEGES"
[httpd] 127.0.0.1 - - [22/Oct/2020:22:37:28 +0000] "POST /query?chunked=true&db=&epoch=ns&q=CREATE+USER+%22admin%22+WITH+PASSWORD+%5BREDACTED%5D+WITH+ALL+PRIVILEGES HTTP/1.1" 200 57 "-" "InfluxDBShell/1.8.3" 2a34bf6a-14b7-11eb-8002-0242c0a85002 126506

```
and these logs

```
[httpd] 127.0.0.1 - admin [22/Oct/2020:22:37:28 +0000] "GET /ping HTTP/1.1" 204 0 "-" "InfluxDBShell/1.8.3" 2a4a8069-14b7-11eb-8003-0242c0a85002 99
ts=2020-10-22T22:37:28.702907Z lvl=info msg="Executing query" log_id=0Q0cCQ90000 service=query query="CREATE DATABASE jlogs"
[httpd] 127.0.0.1 - admin [22/Oct/2020:22:37:28 +0000] "POST /query?chunked=true&db=&epoch=ns&q=CREATE+DATABASE+jlogs HTTP/1.1" 200 57 "-" "InfluxDBShell/1.8.3" 2a4a9d28-14b7-11eb-8004-0242c0a85002 108868

```
Anyhow, if i check on my local directory used for influx data i do not see the db created

```
[root@tig fig]# ls ../influxdb_data/data/
_internal
```

only internal db is created

as a result, when i go to grafana and try to create a data source it fails due to authorization issues (as i'm probably trying to 'connect' to a db that does not exist

Is there a working tag or something i can do to make it work?

**Comment by thomascrha** [comment]
I also couldn't get this to work - the problem seems to be the setting of the META_DIR and then the check in the if statement checking to see if META_DIR is /dev/null (I'm not 100% sure what the check actually does)

```
if [ -z "$INFLUXDB_META_DIR" ]; then
	echo >&2 "setting meta"
	META_DIR="/var/lib/influxdb/meta"
else
	echo >&2 "using meta"
	META_DIR="$INFLUXDB_META_DIR"
fi
```
```
if ( [ ! -z "$INIT_USERS" ] || [ ! -z "$INFLUXDB_DB" ] || [ "$(ls -A /docker-entrypoint-initdb.d 2> /dev/null)" ] ) && [ ! "$(ls -d "$META_DIR" 2>/dev/null)" ]; then
```
It never gets passed this if statement - removing the last part fixed the issue for me. 
here is my version of `init-influxdb.sh`
```
#!/bin/bash
set -e

AUTH_ENABLED="$INFLUXDB_HTTP_AUTH_ENABLED"

if [ -z "$AUTH_ENABLED" ]; then
    echo >&2 'auth not enabled via env'
	AUTH_ENABLED="$(grep -iE '^\s*auth-enabled\s*=\s*true' /etc/influxdb/influxdb.conf | grep -io 'true' | cat)"
else
    echo >&2 'auth set via env'
	AUTH_ENABLED="$(echo "$INFLUXDB_HTTP_AUTH_ENABLED" | grep -io 'true' | cat)"
fi

if [ -z "$INFLUXDB_META_DIR" ]; then
	echo >&2 "setting meta"
	META_DIR="/var/lib/influxdb/meta"
else
	echo >&2 "using meta"
	META_DIR="$INFLUXDB_META_DIR"
fi

INIT_USERS=$([ ! -z "$AUTH_ENABLED" ] && [ ! -z "$INFLUXDB_ADMIN_USER" ] && echo 1 || echo)
echo >&2 $INIT_USERS

if ( [ ! -z "$INIT_USERS" ] || [ ! -z "$INFLUXDB_DB" ] || [ "$(ls -A /docker-entrypoint-initdb.d 2> /dev/null)" ] ); then
    echo >&2 'doing init influx'
	INIT_QUERY=""
	CREATE_DB_QUERY="CREATE DATABASE $INFLUXDB_DB"

	if [ ! -z "$INIT_USERS" ]; then
		echo >&2 "admin user required"
		if [ -z "$INFLUXDB_ADMIN_PASSWORD" ]; then
			INFLUXDB_ADMIN_PASSWORD="$(< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c32;echo;)"
			echo >&2 "INFLUXDB_ADMIN_PASSWORD:$INFLUXDB_ADMIN_PASSWORD"
		fi

		INIT_QUERY="CREATE USER \"$INFLUXDB_ADMIN_USER\" WITH PASSWORD '$INFLUXDB_ADMIN_PASSWORD' WITH ALL PRIVILEGES"
	elif [ ! -z "$INFLUXDB_DB" ]; then
		echo >&2 "database required INFLUXDB_DB"
		INIT_QUERY="$CREATE_DB_QUERY"
	else
		echo >&2 "nothing required"
		INIT_QUERY="SHOW DATABASES"
	fi

	INFLUXDB_INIT_PORT="8086"

	INFLUXDB_HTTP_BIND_ADDRESS=127.0.0.1:$INFLUXDB_INIT_PORT INFLUXDB_HTTP_HTTPS_ENABLED=false influxd "$@" &
	pid="$!"

	INFLUX_CMD="influx -host 127.0.0.1 -port $INFLUXDB_INIT_PORT -execute "
	echo >&2 $pid
	echo >&2 $INFLUX_CMD "$INIT_QUERY"
	for i in {30..0}; do
		if $INFLUX_CMD "$INIT_QUERY" &> /dev/null; then
			break
		fi
		echo >&2 'influxdb init process in progress...'
		sleep 1
	done

	if [ "$i" = 0 ]; then
		echo >&2 'influxdb init process failed.'
		exit 1
	fi

	if [ ! -z "$INIT_USERS" ]; then

		INFLUX_CMD="influx -host 127.0.0.1 -port $INFLUXDB_INIT_PORT -username ${INFLUXDB_ADMIN_USER} -password ${INFLUXDB_ADMIN_PASSWORD} -execute "

		if [ ! -z "$INFLUXDB_DB" ]; then
			$INFLUX_CMD "$CREATE_DB_QUERY"
		fi

		if [ ! -z "$INFLUXDB_USER" ] && [ -z "$INFLUXDB_USER_PASSWORD" ]; then
			INFLUXDB_USER_PASSWORD="$(< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c32;echo;)"
			echo >&2 "INFLUXDB_USER_PASSWORD:$INFLUXDB_USER_PASSWORD"
		fi

		if [ ! -z "$INFLUXDB_USER" ]; then
			$INFLUX_CMD "CREATE USER \"$INFLUXDB_USER\" WITH PASSWORD '$INFLUXDB_USER_PASSWORD'"

			$INFLUX_CMD "REVOKE ALL PRIVILEGES FROM \"$INFLUXDB_USER\""

			if [ ! -z "$INFLUXDB_DB" ]; then
				$INFLUX_CMD "GRANT ALL ON \"$INFLUXDB_DB\" TO \"$INFLUXDB_USER\""
			fi
		fi

		if [ ! -z "$INFLUXDB_WRITE_USER" ] && [ -z "$INFLUXDB_WRITE_USER_PASSWORD" ]; then
			INFLUXDB_WRITE_USER_PASSWORD="$(< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c32;echo;)"
			echo >&2 "INFLUXDB_WRITE_USER_PASSWORD:$INFLUXDB_WRITE_USER_PASSWORD"
		fi

		if [ ! -z "$INFLUXDB_WRITE_USER" ]; then
			$INFLUX_CMD "CREATE USER \"$INFLUXDB_WRITE_USER\" WITH PASSWORD '$INFLUXDB_WRITE_USER_PASSWORD'"
			$INFLUX_CMD "REVOKE ALL PRIVILEGES FROM \"$INFLUXDB_WRITE_USER\""

			if [ ! -z "$INFLUXDB_DB" ]; then
				$INFLUX_CMD "GRANT WRITE ON \"$INFLUXDB_DB\" TO \"$INFLUXDB_WRITE_USER\""
			fi
		fi

		if [ ! -z "$INFLUXDB_READ_USER" ] && [ -z "$INFLUXDB_READ_USER_PASSWORD" ]; then
			INFLUXDB_READ_USER_PASSWORD="$(< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c32;echo;)"
			echo >&2 "INFLUXDB_READ_USER_PASSWORD:$INFLUXDB_READ_USER_PASSWORD"
		fi

		if [ ! -z "$INFLUXDB_READ_USER" ]; then
			$INFLUX_CMD "CREATE USER \"$INFLUXDB_READ_USER\" WITH PASSWORD '$INFLUXDB_READ_USER_PASSWORD'"
			$INFLUX_CMD "REVOKE ALL PRIVILEGES FROM \"$INFLUXDB_READ_USER\""

			if [ ! -z "$INFLUXDB_DB" ]; then
				$INFLUX_CMD "GRANT READ ON \"$INFLUXDB_DB\" TO \"$INFLUXDB_READ_USER\""
			fi
		fi

	fi

	for f in /docker-entrypoint-initdb.d/*; do
		case "$f" in
			*.sh)     echo >&2 "$0: running $f"; . "$f" ;;
			*.iql)    echo >&2 "$0: running $f"; $INFLUX_CMD "$(cat ""$f"")"; echo ;;
			*)        echo >&2 "$0: ignoring $f" ;;
		esac
		echo
	done

	if ! kill -s TERM "$pid" || ! wait "$pid"; then
		echo >&2 'influxdb init process failed. (Could not stop influxdb)'
		exit 1
	fi

fi
```

**Comment by thomascrha** [comment]
Ok the issue for me was with the meta_data directory check with the in the if statement before the init stuff occurs.
```bash
if ( [ ! -z "$INIT_USERS" ] || [ ! -z "$INFLUXDB_DB" ] || [ "$(ls -A /docker-entrypoint-initdb.d 2> /dev/null)" ] ) && [ ! "$(ls -d "$META_DIR" 2>/dev/null)" ]; then
```
The last part is checking if the $META_DIR directory exists - if it does it won't continue. This is important as it's what really see's if the init command have been run and if they needs to be run again. My problem is I don't want to use a volume but a bind - and I can't do that with `/var/lib/influxdb` - so I bind all the sub dirs to get around this i.e. data, wal and meta. When I do this I create the directory - disallowing the init stuff to work. To get around this I simply check if the directory contains any files rather than checking if the directory exists.

What I did was replaced 
```bash
[ ! "$(ls -d "$META_DIR" 2>/dev/null)" ]
```
with 
```bash
[ $(ls "$META_DIR" | wc -l  | grep -w "0") ]
```

**Comment by andcan86** [comment]
it might have to do with the OS, on Windows 10 I have to use double quotes for the environement variables, so:

INFLUXDB_DB="db-test"

hope that helps

**Comment by suadev** [comment]
that's worked for me

```
  influxdb:
    image: influxdb:latest
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: password
      DOCKER_INFLUXDB_INIT_ORG: myorg
      DOCKER_INFLUXDB_INIT_BUCKET: krakend
    ports:
      - "8086:8086"
  ```

**Comment by sailesh-suri** [comment]
If you're still using influxdb:1.8, you'll need to set a custom meta DB directory with the `INFLUXDB_META_DIR` environment variable. The `/init-influxdb.sh` script that's supposed to create your admin user account does not seem to function if you use the default meta directory. Not sure why it was designed that way. The below configuration is working for me. 

```
  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=default-db
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=password
      - INFLUXDB_META_DIR=/var/lib/influxdb/meta2
 ```

**Comment by sakeebs** [comment]
Do we have any solution for this, as after every restart of the container or docker service or server reboot I have to change the meta DIR variable.

- INFLUXDB_META_DIR=/var/lib/influxdb/meta2

**Comment by iUnstable0** [comment]
This issue is still happening :(
